"""Render the 'Chantie' wordmark to an RGB565 bitmap header.

Script-style font (Segoe Script, fallback Ink Free/Gabriola), warm pink, with
a little heart, composited on the light page background so the firmware can
blit it without alpha. Writes firmware/esp32_glucose/chantie_logo.h.
"""
import os
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

BG = (242, 243, 242)        # DX_BG in display.h (0xF79E)
PINK = (233, 84, 128)
PINK_D = (196, 50, 96)

for cand in (r"C:\Windows\Fonts\segoescb.ttf", r"C:\Windows\Fonts\segoesc.ttf",
             r"C:\Windows\Fonts\inkfree.ttf", r"C:\Windows\Fonts\Gabriola.ttf"):
    if os.path.exists(cand):
        FONT = cand
        break
print("font:", FONT)

font = ImageFont.truetype(FONT, 44)
text = "Chantie"
bbox = font.getbbox(text)
tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
W, H = tw + 34, th + 12
img = Image.new("RGB", (W, H), BG)
d = ImageDraw.Draw(img)
d.text((2 - bbox[0], 6 - bbox[1]), text, font=font, fill=PINK)

# little heart after the name: two circles + a triangle
hx, hy, s = tw + 12, H // 2 - 2, 7
d.polygon([(hx - s, hy), (hx + s, hy), (hx, hy + int(s * 1.3))], fill=PINK_D)
d.ellipse([hx - s, hy - s + 1, hx, hy + 2], fill=PINK_D)
d.ellipse([hx, hy - s + 1, hx + s, hy + 2], fill=PINK_D)

def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

out = Path(__file__).resolve().parent.parent / "firmware" / "esp32_glucose" / "chantie_logo.h"
px = img.load()
with open(out, "w") as f:
    f.write("// Generated by tools/make_chantie_logo.py\n")
    f.write("#ifndef CHANTIE_LOGO_H\n#define CHANTIE_LOGO_H\n#include <stdint.h>\n")
    f.write(f"#define CHANTIE_LOGO_W {W}\n#define CHANTIE_LOGO_H {H}\n")
    f.write(f"static const uint16_t CHANTIE_LOGO[{W * H}] = {{\n")
    vals = [rgb565(*px[x, y]) for y in range(H) for x in range(W)]
    for i in range(0, len(vals), 16):
        f.write("  " + ",".join("0x%04X" % v for v in vals[i:i+16]) + ",\n")
    f.write("};\n#endif\n")
print(f"wrote {out} ({W}x{H}, {W*H*2} bytes)")
