"""TTF -> Adafruit GFXfont header converter (for Arduino_GFX setFont).

Renders each glyph with Pillow at the requested pixel size, thresholds to
1-bit, and packs the standard GFXfont structures. Glyph metrics follow the
GFX convention: yOffset is relative to the baseline (negative above).

Usage: edit FONTS below and run; writes the header to stdout target path.
"""
from PIL import Image, ImageDraw, ImageFont

import string
FONTS = [
    # (name, ttf, px, charset)
    ("GlucoseBig", r"C:\Windows\Fonts\segoeuib.ttf", 76, "0123456789.,"),
    ("UiMed",      r"C:\Windows\Fonts\segoeuib.ttf", 26, None),   # None = ASCII 32..126
    ("UiSmall",    r"C:\Windows\Fonts\segoeui.ttf",  17, None),
    # the owner's name renders in script at runtime, whatever it is
    ("NameScript", r"C:\Windows\Fonts\segoescb.ttf", 38, " " + string.ascii_letters),
]
import os
OUT = os.path.join(os.path.dirname(__file__), "..", "firmware", "esp32_glucose", "fonts.h")


def build_font(name, path, px, charset):
    font = ImageFont.truetype(path, px)
    ascent, descent = font.getmetrics()
    chars = charset if charset else "".join(chr(c) for c in range(32, 127))
    first, last = ord(min(chars)), ord(max(chars))
    bitmap = bytearray()
    glyphs = []
    for code in range(first, last + 1):
        ch = chr(code)
        if ch not in chars:
            glyphs.append((len(bitmap), 0, 0, px // 3, 0, 0))
            continue
        adv = max(1, round(font.getlength(ch)))
        bbox = font.getbbox(ch)
        if bbox is None or bbox[2] - bbox[0] == 0 or bbox[3] - bbox[1] == 0:
            glyphs.append((len(bitmap), 0, 0, adv, 0, 0))   # space etc.
            continue
        x0, y0, x1, y1 = bbox
        w, h = x1 - x0, y1 - y0
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-x0, -y0), ch, fill=255, font=font)
        px_data = img.load()
        off = len(bitmap)
        bits, nbits = 0, 0
        for yy in range(h):
            for xx in range(w):
                bits = (bits << 1) | (1 if px_data[xx, yy] >= 128 else 0)
                nbits += 1
                if nbits == 8:
                    bitmap.append(bits)
                    bits, nbits = 0, 0
        if nbits:
            bitmap.append(bits << (8 - nbits))
        glyphs.append((off, w, h, adv, x0, y0 - ascent))
    y_advance = ascent + descent
    return first, last, bitmap, glyphs, y_advance


with open(OUT, "w") as f:
    f.write("// Generated by tools/aimelo/ttf2gfx.py from Segoe UI -- modern\n")
    f.write("// proportional fonts in Adafruit GFXfont format.\n")
    f.write("#ifndef FONTS_H\n#define FONTS_H\n#include <Arduino_GFX_Library.h>\n\n")
    for name, path, px, charset in FONTS:
        first, last, bitmap, glyphs, ya = build_font(name, path, px, charset)
        f.write(f"static const uint8_t {name}_bmp[] PROGMEM = {{\n")
        for i in range(0, len(bitmap), 16):
            f.write("  " + ",".join(f"0x{b:02X}" for b in bitmap[i:i+16]) + ",\n")
        f.write("};\n")
        f.write(f"static const GFXglyph {name}_gl[] PROGMEM = {{\n")
        for g in glyphs:
            f.write("  {%d,%d,%d,%d,%d,%d},\n" % g)
        f.write("};\n")
        f.write(f"static const GFXfont {name} = {{ (uint8_t*){name}_bmp, "
                f"(GFXglyph*){name}_gl, {first}, {last}, {ya} }};\n\n")
        print(f"{name}: {len(bitmap)} B bitmap, {len(glyphs)} glyphs, yAdvance {ya}")
    f.write("#endif\n")
print("wrote", OUT)
